### ISSUE TITLE
Feedcord update broke?

### ISSUE THREAD

**Issue by YoshiOST** [Qolors/FeedCord#14]
I've been getting
"error while creating mount source path" for a while. 
I have updated the appsettings.json format, but haven't moved it anywhere new.
root folder I put the yaml and using the docker cli commands.
before the 2.0.0 update, it seemed fine.
![vhDq4F7VRp](https://github.com/Qolors/FeedCord/assets/104037569/e9a32cd3-bfba-4b3e-8e20-bff0c6f5e276)

I'm using window 10, wsl2

**Comment by Qolors** [comment]
Hey there! I'm having no luck in reproducing this..

Have you tried creating a new Folder with the required files and see if it gives you any luck?

- Create a `FeedCord_Test` Folder (or whatever you wish to call it)
- Put your 2.0+ updated `appsettings.json` file in the base of this folder
- Insert this docker-compose.yaml file in the new folder:

```
version: "3.9"

services:
  myfeedcord:
    image: qolors/feedcord:latest
    container_name: FeedCord
    restart: unless-stopped
    volumes:
      - ./appsettings.json:/app/config/appsettings.json
```

See if this runs correctly - we can see if it's a folder and/or file permissions issue by chance. Report back and I'll be happy to try to figure this out for you. Thanks
