### ISSUE TITLE
appsettings.json or config.json?

### ISSUE THREAD

**Issue by 101br03k** [Qolors/FeedCord#18]
main page: docker-compose.yml 
```
version: "3.9"

services:
  myfeedcord:
    image: qolors/feedcord:latest # for amd64 architecture
    # image: qolors/feedcord:latest-arm64  # For arm64 architecture (Uncomment this line and comment the above if using arm64)
    container_name: FeedCord
    restart: unless-stopped
    volumes:
      - ./PATH/TO/MY/JSON/FILE/appsettings.json:/app/config/appsettings.json
```

but on the migration guide its called config.json
Should I also then connect it with the volume to config.json?
Like so: 
`- ./PATH/TO/MY/JSON/FILE/congif.json:/app/config/config.json`

Because the migration guide does not have a compose file, while in the migration guide the appsettings.json is not refferenced.
